{
 "title": "TOP LEVEL ALL ENVOYS",
 "panels": [
  {
   "title": "RPS",
   "type": "graph",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(envoy_http_downstream_rq_total[1m]))",
     "legendFormat": "Globlal RPS"
    },
    {
     "expr": "sum(rate(envoy_cluster_health_check_attempt[1m]))",
     "legendFormat": "Global HC RPS"
    },
    {
     "expr": "sum(rate(envoy_http_rq_total[1m]))",
     "legendFormat": "Global Routed RPS"
    }
   ]
  },
  {
   "title": "Global CPS",
   "type": "graph",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(envoy_http_downstream_cx_total[1m]))",
     "legendFormat": "Global CPS"
    }
   ]
  },
  {
   "title": "Success Rate (non-5xx responses)",
   "type": "graph",
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "(1 - (sum(rate(envoy_http_downstream_rq_xx{response_code_class=\"5\"}[1m])) / sum(rate(envoy_http_downstream_rq_xx[1m]))))",
     "legendFormat": "SR"
    }
   ]
  },
  {
   "title": "Connections",
   "type": "graph",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(envoy_http_downstream_cx_active)",
     "legendFormat": "Global Connections"
    },
    {
     "expr": "sum(envoy_server_parent_connections)",
     "legendFormat": "Global Parent Connections"
    }
   ]
  },
  {
   "title": "Upstream failures",
   "type": "graph",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(envoy_cluster_upstream_rq_pending_failure_eject[1m]))",
     "legendFormat": "Pending failure ejection"
    },
    {
     "expr": "sum(rate(envoy_cluster_upstream_rq_pending_overflow[1m]))",
     "legendFormat": "Pending Overflow"
    },
    {
     "expr": "sum(rate(envoy_cluster_upstream_cx_connect_timeout[1m]))",
     "legendFormat": "Connect Timeout"
    },
    {
     "expr": "sum(rate(envoy_cluster_upstream_rq_timeout[1m]))",
     "legendFormat": "Request Timeout"
    }
   ]
  },
  {
   "title": "Upstream Retries",
   "type": "graph",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(envoy_cluster_upstream_rq_retry[1m]))",
     "legendFormat": "Retry"
    },
    {
     "expr": "sum(rate(envoy_cluster_upstream_rq_retry_success[1m]))",
     "legendFormat": "Retry Success"
    },
    {
     "expr": "sum(rate(envoy_cluster_upstream_rq_retry_overflow[1m]))",
     "legendFormat": "Retry Overflow"
    }
   ]
  },
  {
   "title": "Outlier Detection",
   "type": "graph",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(envoy_cluster_outlier_detection_ejections_enforced_total[1m]))",
     "legendFormat": "Total Ejections"
    },
    {
     "expr": "sum(rate(envoy_cluster_outlier_detection_ejections_overflow[1m]))",
     "legendFormat": "Total Ejection Overflows"
    }
   ]
  },
  {
   "title": "Health Checks",
   "type": "graph",
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "((sum(rate(envoy_cluster_health_check_success[1m])) / sum(rate(envoy_cluster_health_check_attempt[1m]))))",
     "legendFormat": "Success Rate"
    }
   ]
  }
 ]
}
{
 "title": "Global Versions",
 "panels": [
  {
   "title": "Max Version",
   "type": "singlestat",
   "format": "none",
   "valueName": "avg",
   "targets": [
    { "expr": "max(envoy_server_version)" }
   ]
  },
  {
   "title": "Min Version",
   "type": "singlestat",
   "format": "none",
   "valueName": "avg",
   "targets": [
    { "expr": "min(envoy_server_version)" }
   ]
  }
 ]
}
{
 "title": "Egress from [[originating_service]] to [[destination_service]]",
 "panels": [
  {
   "title": "Egress CPS / RPS",
   "type": "graph",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(envoy_cluster_upstream_cx_total{instance=~\"[[originating_instance]]\",app=\"[[originating_service]]\",envoy_cluster_name=\"[[destination_service]]\"}[1m]))",
     "legendFormat": "egress CPS"
    },
    {
     "expr": "sum(rate(envoy_cluster_upstream_rq_total{instance=~\"[[originating_instance]]\",app=\"[[originating_service]]\",envoy_cluster_name=\"[[destination_service]]\"}[1m]))",
     "legendFormat": "egress RPS"
    },
    {
     "expr": "sum(rate(envoy_cluster_upstream_rq_pending_total{instance=~\"[[originating_instance]]\",app=\"[[originating_service]]\",envoy_cluster_name=\"[[destination_service]]\"}[1m]))",
     "legendFormat": "pending req to"
    },
    {
     "expr": "sum(rate(envoy_cluster_lb_healthy_panic{instance=~\"[[originating_instance]]\",app=\"[[originating_service]]\",envoy_cluster_name=\"[[destination_service]]\"}[1m]))",
     "legendFormat": "lb healthy panic RPS"
    }
   ]
  },
  {
   "title": "Total Connections / Requests",
   "type": "graph",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(envoy_cluster_upstream_cx_active{instance=~\"[[originating_instance]]\",app=\"[[originating_service]]\",envoy_cluster_name=\"[[destination_service]]\"})",
     "legendFormat": "connections"
    },
    {
     "expr": "sum(envoy_cluster_upstream_rq_active{instance=~\"[[originating_instance]]\",app=\"[[originating_service]]\",envoy_cluster_name=\"[[destination_service]]\"})",
     "legendFormat": "requests"
    },
    {
     "expr": "sum(envoy_cluster_upstream_rq_pending_active{instance=~\"[[originating_instance]]\",app=\"[[originating_service]]\",envoy_cluster_name=\"[[destination_service]]\"})",
     "legendFormat": "pending"
    }
   ]
  },
  {
   "title": "Cluster Membership",
   "type": "graph",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(delta(envoy_cluster_membership_change{instance=~\"[[originating_instance]]\",app=\"[[originating_service]]\",envoy_cluster_name=\"[[destination_service]]\"}[1m]))",
     "legendFormat": "membership changes [1m]"
    },
    {
     "expr": "sum(envoy_cluster_membership_total{instance=~\"[[originating_instance]]\",app=\"[[originating_service]]\",envoy_cluster_name=\"[[destination_service]]\"})",
     "legendFormat": "total membershiip"
    },
    {
     "expr": "sum(envoy_cluster_outlier_detection_ejections_active{instance=~\"[[originating_instance]]\",app=\"[[originating_service]]\",envoy_cluster_name=\"[[destination_service]]\"})",
     "legendFormat": "outlier ejections active"
    },
    {
     "expr": "sum(envoy_cluster_membership_healthy{instance=~\"[[originating_instance]]\",app=\"[[originating_service]]\",envoy_cluster_name=\"[[destination_service]]\"})",
     "legendFormat": "healthy members (active HC and outlier)"
    },
    {
     "expr": "sum(envoy_cluster_health_check_healthy{instance=~\"[[originating_instance]]\",app=\"[[originating_service]]\",envoy_cluster_name=\"[[destination_service]]\"})",
     "legendFormat": "healthy members (active HC only)"
    }
   ]
  },
  {
   "title": "Success Rate (non-5xx responses)",
   "type": "graph",
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum(rate(envoy_cluster_upstream_rq_xx{response_code_class!=\"5\",instance=~\"[[originating_instance]]\",app=\"[[originating_service]]\",envoy_cluster_name=\"[[destination_service]]\"}[1m])) / sum(rate(envoy_cluster_upstream_rq_xx{instance=~\"[[originating_instance]]\",app=\"[[originating_service]]\",envoy_cluster_name=\"[[destination_service]]\"}[1m]))",
     "legendFormat": "Success Rate %"
    }
   ]
  },
  {
   "title": "4xx %",
   "type": "graph",
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum(rate(envoy_cluster_upstream_rq_xx{response_code_class=\"4\",instance=~\"[[originating_instance]]\",app=\"[[originating_service]]\",envoy_cluster_name=\"[[destination_service]]\"}[1m])) / sum(rate(envoy_cluster_upstream_rq_xx{instance=~\"[[originating_instance]]\",app=\"[[originating_service]]\",envoy_cluster_name=\"[[destination_service]]\"}[1m]))",
     "legendFormat": "%"
    }
   ]
  },
  {
   "title": "Upstream Request Errors",
   "type": "graph",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(envoy_cluster_upstream_cx_connect_timeout{instance=~\"[[originating_instance]]\",app=\"[[originating_service]]\",envoy_cluster_name=\"[[destination_service]]\"}[1m]))",
     "legendFormat": "connect timeout"
    },
    {
     "expr": "sum(rate(envoy_cluster_upstream_rq_pending_failure_eject{instance=~\"[[originating_instance]]\",app=\"[[originating_service]]\",envoy_cluster_name=\"[[destination_service]]\"}[1m]))",
     "legendFormat": "pending failure ejection"
    },
    {
     "expr": "sum(rate(envoy_cluster_upstream_rq_pending_overflow{instance=~\"[[originating_instance]]\",app=\"[[originating_service]]\",envoy_cluster_name=\"[[destination_service]]\"}[1m]))",
     "legendFormat": "pending overflow"
    },
    {
     "expr": "sum(rate(envoy_cluster_upstream_rq_timeout{instance=~\"[[originating_instance]]\",app=\"[[originating_service]]\",envoy_cluster_name=\"[[destination_service]]\"}[1m]))",
     "legendFormat": "request timeout"
    },
    {
     "expr": "sum(rate(envoy_cluster_upstream_rq_per_try_timeout{instance=~\"[[originating_instance]]\",app=\"[[originating_service]]\",envoy_cluster_name=\"[[destination_service]]\"}[1m]))",
     "legendFormat": "per try request timeout"
    },
    {
     "expr": "sum(rate(envoy_cluster_upstream_rq_rx_reset{instance=~\"[[originating_instance]]\",app=\"[[originating_service]]\",envoy_cluster_name=\"[[destination_service]]\"}[1m]))",
     "legendFormat": "request reset"
    },
    {
     "expr": "sum(rate(envoy_cluster_upstream_cx_destroy_local_with_active_rq{instance=~\"[[originating_instance]]\",app=\"[[originating_service]]\",envoy_cluster_name=\"[[destination_service]]\"}[1m]))",
     "legendFormat": "destroy initialized from originating service"
    },
    {
     "expr": "sum(rate(envoy_http_downstream_cx_destroy_remote_active_rq{instance=~\"[[originating_instance]]\",app=\"[[originating_service]]\",envoy_cluster_name=\"[[destination_service]]\"}[1m]))",
     "legendFormat": "destroy initialized from remote service"
    },
    {
     "expr": "sum(rate(envoy_cluster_upstream_rq_maintenance_mode{instance=~\"[[originating_instance]]\",app=\"[[originating_service]]\",envoy_cluster_name=\"[[destination_service]]\"}[1m]))",
     "legendFormat": "request failed maintenance mode"
    }
   ]
  },
  {
   "title": "Upstream Request Retry",
   "type": "graph",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(envoy_cluster_upstream_rq_retry{instance=~\"[[originating_instance]]\",app=\"[[originating_service]]\",envoy_cluster_name=\"[[destination_service]]\"}[1m]))",
     "legendFormat": "request retry"
    },
    {
     "expr": "sum(rate(envoy_cluster_upstream_rq_retry_success{instance=~\"[[originating_instance]]\",app=\"[[originating_service]]\",envoy_cluster_name=\"[[destination_service]]\"}[1m]))",
     "legendFormat": "request retry success"
    },
    {
     "expr": "sum(rate(envoy_cluster_upstream_rq_retry_overflow{instance=~\"[[originating_instance]]\",app=\"[[originating_service]]\",envoy_cluster_name=\"[[destination_service]]\"}[1m]))",
     "legendFormat": "request retry overflow"
    }
   ]
  },
  {
   "title": "Upstream Flow Control",
   "type": "graph",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(envoy_cluster_upstream_flow_control_paused_reading_total{instance=~\"[[originating_instance]]\",app=\"[[originating_service]]\",envoy_cluster_name=\"[[destination_service]]\"}[1m]))",
     "legendFormat": "paused reading from destination service"
    },
    {
     "expr": "sum(rate(envoy_cluster_upstream_flow_control_resumed_reading_total{instance=~\"[[originating_instance]]\",app=\"[[originating_service]]\",envoy_cluster_name=\"[[destination_service]]\"}[1m]))",
     "legendFormat": "resumed reading from destination service"
    },
    {
     "expr": "sum(rate(envoy_cluster_upstream_flow_control_backed_up_total{instance=~\"[[originating_instance]]\",app=\"[[originating_service]]\",envoy_cluster_name=\"[[destination_service]]\"}[1m]))",
     "legendFormat": "paused reading from originating service"
    },
    {
     "expr": "sum(rate(envoy_cluster_upstream_flow_control_drained_total{instance=~\"[[originating_instance]]\",app=\"[[originating_service]]\",envoy_cluster_name=\"[[destination_service]]\"}[1m]))",
     "legendFormat": "resumed reading from originating service"
    }
   ]
  },
  {
   "title": "Outlier Detection",
   "type": "graph",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(envoy_cluster_outlier_detection_ejections_enforced_total{instance=~\"[[originating_instance]]\",app=\"[[originating_service]]\",envoy_cluster_name=\"[[destination_service]]\"}[1m]))",
     "legendFormat": "Total ejections"
    },
    {
     "expr": "sum(rate(envoy_cluster_outlier_detection_ejections_overflow{instance=~\"[[originating_instance]]\",app=\"[[originating_service]]\",envoy_cluster_name=\"[[destination_service]]\"}[1m]))",
     "legendFormat": "Total ejection overflows"
    }
   ]
  },
  {
   "title": "Upstream Response Time",
   "type": "graph",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum(rate(envoy_cluster_upstream_rq_time_bucket{instance=~\"[[originating_instance]]\",app=\"[[originating_service]]\",envoy_cluster_name=\"[[destination_service]]\"}[1m])) by (le))",
     "legendFormat": "50th %ile"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(envoy_cluster_upstream_rq_time_bucket{instance=~\"[[originating_instance]]\",app=\"[[originating_service]]\",envoy_cluster_name=\"[[destination_service]]\"}[1m])) by (le))",
     "legendFormat": "95th %ile"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(envoy_cluster_upstream_rq_time_bucket{instance=~\"[[originating_instance]]\",app=\"[[originating_service]]\",envoy_cluster_name=\"[[destination_service]]\"}[1m])) by (le))",
     "legendFormat": "99th %ile"
    }
   ]
  }
 ]
}
{
 "title": "Circuit breaking",
 "panels": [
  {
   "title": "[[originating_service]] to [[destination_service]] retry overflow",
   "type": "graph",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(envoy_cluster_upstream_rq_retry_overflow{instance=~\"[[originating_instance]]\",app=\"[[originating_service]]\",envoy_cluster_name=\"[[destination_service]]\"})",
     "legendFormat": "overflows"
    }
   ]
  },
  {
   "title": "[[originating_service]] to [[destination_service]] connection overflow",
   "type": "graph",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(envoy_cluster_upstream_cx_overflow{instance=~\"[[originating_instance]]\",app=\"[[originating_service]]\",envoy_cluster_name=\"[[destination_service]]\"})"
    }
   ]
  },
  {
   "title": "[[originating_service]] to [[destination_service]] request overflow",
   "type": "graph",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(envoy_cluster_upstream_rq_pending_overflow{instance=~\"[[originating_instance]]\",app=\"[[originating_service]]\",envoy_cluster_name=\"[[destination_service]]\"})",
     "legendFormat": "overflows"
    }
   ]
  },
  {
   "title": "[[destination_service]] request overflow",
   "type": "graph",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(envoy_cluster_upstream_rq_pending_overflow{app=\"[[destination_service]]\",envoy_cluster_name=\"local_service_[[destination_service]]\"})"
    }
   ]
  },
  {
   "title": "[[destination_service]] connection overflow",
   "type": "graph",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(envoy_cluster_upstream_cx_overflow{app=\"[[destination_service]]\",envoy_cluster_name=\"local_service_[[destination_service]]\"})"
    }
   ]
  }
 ]
}
{
 "title": "[[destination_service]] INGRESS",
 "panels": [
  {
   "title": "Ingress CPS / RPS",
   "type": "graph",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(envoy_http_rq_total{app=\"[[destination_service]]\",http_conn_manager_prefix=\"ingress_[[destination_service]]_http\"}[1m]))",
     "legendFormat": "RPS"
    },
    {
     "expr": "sum(rate(envoy_http_downstream_cx_total{app=\"[[destination_service]]\",http_conn_manager_prefix=\"ingress_[[destination_service]]_http\"}[1m]))",
     "legendFormat": "CPS"
    }
   ]
  }
 ]
}
{
 "title": "gRPC Metrics",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Total Requests",
   "type": "stat",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "expr": "sum(grpc_requests_total)" }
   ]
  },
  {
   "title": "Request Latency p95",
   "type": "timeseries",
   "description": "The histogram_quantile function uses the data from sum(rate(grpc_request_latency_seconds_bucket[1m])) to estimate the latency value at the 95th percentile. In other words, it calculates the value below which 95% of the requests fall.",
   "gridPos": { "h": 10, "w": 16, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(grpc_request_latency_seconds_bucket[1m])) by (le))",
     "legendFormat": "p95"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(grpc_request_latency_seconds_bucket[1m])) by (le))",
     "legendFormat": "p99"
    },
    {
     "expr": "histogram_quantile(0.50, sum(rate(grpc_request_latency_seconds_bucket[1m])) by (le))",
     "legendFormat": "p50"
    }
   ]
  },
  {
   "title": "Rate of gRPC requests processed per second over the last minute",
   "type": "timeseries",
   "description": "gives you the total rate of gRPC requests processed per second over the last minute, aggregated across all instances or services that report this metric. ",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "sum(rate(grpc_requests_total[1m]))",
     "legendFormat": "Total Requests Processed per Second"
    }
   ]
  },
  {
   "title": "Rate of gRPC Requests in the Last 5 Minutes per Pod",
   "type": "timeseries",
   "description": "The result of this query will be the total number of grpc_requests_total that have occurred within the past 5 minutes. ",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 19 },
   "targets": [
    {
     "expr": "increase(grpc_requests_total[5m])",
     "legendFormat": "{{kubernetes_pod_name}}"
    }
   ]
  }
 ]
}