apiVersion: v1
kind: ConfigMap
metadata:
  name: argo-rollouts-config
  namespace: {{ .Values.namespace }}
data:
  trafficRouterPlugins: |-
    - name: "argoproj-labs/gatewayAPI"
      location: "https://github.com/argoproj-labs/rollouts-plugin-trafficrouter-gatewayapi/releases/download/v0.0.0-rc1/gateway-api-plugin-linux-amd64"