apiVersion: batch/v1
kind: Job
metadata:
  name: echo-load-test
spec:
  template:
    spec:
      containers:
      - name: echo-load-test
        image: nurnechushtan/echo-load-test:fbc6c690e701d2156a4c28153cef752c5b8309a0
      restartPolicy: Never