apiVersion: batch/v1
kind: Job
metadata:
  name: echo-load-test
spec:
  template:
    spec:
      containers:
      - name: echo-load-test
        image: nurnechushtan/echo-load-test:b2dd3319cfee5574385db36ee98267d87fde7603
      restartPolicy: Never