apiVersion: batch/v1
kind: Job
metadata:
  name: echo-load-test
spec:
  template:
    spec:
      containers:
      - name: echo-load-test
        image: nurnechushtan/echo-load-test:7f1e2bf1abc684ee1eee34355bf7555bad6b1be1
      restartPolicy: Never