apiVersion: batch/v1
kind: Job
metadata:
  name: echo-load-test
spec:
  template:
    spec:
      containers:
      - name: echo-load-test
        image: nurnechushtan/echo-load-test:6b963ae4b021f79ca7bffdc66afd1fcc4e5a3e4a
      restartPolicy: Never