apiVersion: batch/v1
kind: Job
metadata:
  name: prometheus-adapter-job
  annotations:
    "helm.sh/hook": post-install
    "helm.sh/hook-delete-policy": hook-succeeded
spec:
  template:
    spec:
      restartPolicy: OnFailure
      containers:
      - name: prometheus-adapter
        image: dtzar/helm-kubectl:3.14.2
        command:
        - /bin/sh
        - -c
        - |          
          # Add the prometheus-community repository
          helm repo add prometheus-community https://prometheus-community.github.io/helm-charts

          # Update the repo to make sure we have the latest charts
          helm repo update

          ls -l
          pwd

          # Check if the prometheus-adapter release exists and update it
          if helm ls -n prometheus | grep -q prometheus-adapter ; then
            helm upgrade prometheus-adapter prometheus-community/prometheus-adapter --values prometheus/templates/prometheus-adapter-values.yaml --namespace prometheus
          else
            helm install prometheus-adapter prometheus-community/prometheus-adapter --values prometheus/templates/prometheus-adapter-values.yaml --namespace prometheus
          fi
      restartPolicy: Never
