apiVersion: batch/v1
kind: Job
metadata:
  name: prometheus-adapter-job
  annotations:
    "helm.sh/hook": post-install
    "helm.sh/hook-delete-policy": hook-succeeded
spec:
  template:
    spec:
      restartPolicy: OnFailure
      containers:
        - name: prometheus-adapter
          image: dtzar/helm-kubectl:3.14.2
          command:
            - /bin/sh
            - -c
            - |
              if ! helm ls -n prometheus | grep -q prometheus-adapter ; then
                helm repo add prometheus-community https://prometheus-community.github.io/helm-charts
                helm install prometheus-adapter prometheus-community/prometheus-adapter --values /etc/config/config --namespace prometheus
              fi
          volumeMounts:
          - name: config-volume
            mountPath: /etc/config
      volumes:
      - name: config-volume
        configMap:
          name: prometheus-adapter-config
      restartPolicy: Never