apiVersion: v1
kind: Service
metadata:
  name: prometheus-service
  namespace: {{ .Values.appName }}
spec:
  selector:
    app: {{ .Values.appName }}
  ports:
  - protocol: TCP
    port: 80
    targetPort: 9090
