apiVersion: argoproj.io/v1alpha1
kind: AnalysisTemplate
metadata:
  name: success-rate
spec:
  # args:
  # - name: target
  # - name: namespace
  # - name: prometheus-port
  #   value: 9090
  metrics:
  - name: success-rate
    interval: 1m
    successCondition: result[0] >= 0.95
    failureLimit: 3
    provider:
      prometheus:
        address: http://prometheus.linkerd-viz:9090        
        query: |
          sum(
            rate(
              response_total{
                namespace="{{ .Values.appName }}",
                deployment=~"rollouts-audio-transformer-service",
                classification!="failure",
                direction="inbound"
              }[{{ interval }}]
            )
          ) 
          / 
          sum(
            rate(
              response_total{
                namespace="{{ namespace }}",
                deployment=~"{{ target }}",
                direction="inbound"
              }[{{ interval }}]
            )
          ) 
          * 100
