apiVersion: argoproj.io/v1alpha1
kind: AnalysisTemplate
metadata:
  name: latency-check
spec:
  metrics:
  - name: latency-check
    successCondition: result[0] <= 2
    failureLimit: 3
    provider:
      prometheus:
        address: http://prometheus.linkerd-viz:9090        
        query: |
          avg(
            rate(
              response_latency_ms_sum{
                namespace="{{ .Values.appName }}",
                app="{{ .Values.appName }}",
                direction="inbound"
              }[1m]
            )
          ) 
          / 
          avg(
            rate(
              response_latency_ms_count{
                namespace="{{ .Values.appName }}",
                app="{{ .Values.appName }}",
                direction="inbound"
              }[1m]
            )
          )