apiVersion: argoproj.io/v1alpha1
kind: AnalysisTemplate
metadata:
  name: success-rate
spec:
  metrics:
  - name: success-rate
    successCondition: result[0] >= 0.98
    failureLimit: 3
    provider:
      prometheus:
        address: http://prometheus.linkerd-viz:9090        
        query: |
          sum(
            rate(
              response_total{
                namespace="{{ .Values.appName }}",
                app="{{ .Values.appName }}",
                classification!="failure",
                direction="inbound"
              }[1m]
            )
          ) 
          / 
          sum(
            rate(
              response_total{
                namespace="{{ .Values.appName }}",
                app="{{ .Values.appName }}",
                direction="inbound"
              }[1m]
            )
          ) 
          * 100
