apiVersion: batch/v1
kind: Job
metadata:
  name: echo-load-test
  annotations:
    argocd.argoproj.io/hook: PostSync
    argocd.argoproj.io/hook-delete-policy: HookSucceeded
spec:
  template:
    spec:
      containers:
      - name: echo-load-test
        image: grafana/k6:latest
        command: ["sh", "-c"]
        args: ["k6 run - < /app/load-test-echo.js"]
        volumeMounts:
        - name: echo-load-test-volume
          mountPath: /app
      volumes:
      - name: echo-load-test-volume
        configMap:
          name: echo-load-test
      restartPolicy: Never