apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: audio-transformer-service-custom-hpa
  namespace: {{ .Values.appName }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ .Values.appName }}
  minReplicas: 1
  maxReplicas: 15
  metrics:
    - type: Pods
      pods:
        metric:
          name: http_requests_per_second
        target:
          type: AverageValue
          averageValue: 15000m