apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: audio-transformer-service-custom-hpa
  namespace: {{ .Values.appName }}
spec:
  scaleTargetRef:
    apiVersion: argoproj.io/v1alpha1
    kind: Rollout
    name: rollouts-{{ .Values.appName }}
  minReplicas: 3
  maxReplicas: 15
  metrics:
    - type: Pods
      pods:
        metric:
          name: http_requests_per_second
        target:
          type: AverageValue
          averageValue: 10000m