apiVersion: batch/v1
kind: Job
metadata:
  name: {{ .Release.Name }}-linkerd-inject
  annotations:
    "helm.sh/hook": post-install,post-upgrade
spec:
  template:
    spec:
      restartPolicy: OnFailure
      containers:
        - name: linkerd-inject
          image: bitnami/kubectl:latest
          command: ["/bin/sh", "-c"]
          args:
            - >
              apk add --no-cache curl &&
              curl -sL https://run.linkerd.io/install | sh &&
              export PATH=$PATH:$HOME/.linkerd2/bin &&
              kubectl get deploy {{ .Values.appName }} -n {{ .Values.appName }} -o yaml | 
              linkerd inject - | 
              kubectl apply -f -