apiVersion: batch/v1
kind: Job
metadata:
  name: {{ .Release.Name }}-linkerd-inject
  annotations:
    "helm.sh/hook": post-install,post-upgrade
spec:
  template:
    spec:
      restartPolicy: OnFailure
      containers:
        - name: linkerd-inject
          image: lachlanevenson/k8s-kubectl:latest
          command: ["/bin/sh", "-c"]
          args:
            - >
              curl --proto '=https' --tlsv1.2 -sSfL https://run.linkerd.io/install-edge | sh &&
              export PATH=$HOME/.linkerd2/bin:$PATH &&
              echo linkerd version: $(linkerd version) &&
              kubectl get deployments.apps {{ .Values.appName }} -n {{ .Values.appName }} -o yaml | 
              linkerd inject - | 
              kubectl apply -f -