apiVersion: v1
kind: Service
metadata:
  name: audio-transformer-service-canary-service
  namespace: {{ .Values.appName }}
spec:
  selector:
    app: {{ .Values.appName }}
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
