apiVersion: v1
kind: Service
metadata:
  name: song-service-headless
  labels:
    app: {{ .Values.appName }}
  namespace: {{ .Values.appName }}
spec:
  type: ClusterIP
  clusterIP: None
  selector:
    app: {{ .Values.appName }}
  ports:
    - protocol: TCP
      name: grpc
      port: 50051
      targetPort: 50051
