on: push
name: deploy
jobs:
  deploy:
    name: deploy to cluster
    runs-on: ubuntu-latest
    steps:
    - name: Kubectl tool installer
      uses: Azure/setup-kubectl@v1

    - name: Setup kubectl
      env: 
        K8S_CONFIG: ${{ secrets.KUBE_CONFIG_DATA }}
      run: |
        mkdir -p $HOME/.kube
        echo "${K8S_CONFIG}" | base64 --decode > $HOME/.kube/config
      
    - name: Download Deploy
      uses: actions/download-artifact@v2
      with:
        name: deploy
      
    - name: Apply pods
      run: kubectl apply -f gateway/ns.yaml
