on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main

jobs:

  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@3b5e8027fcad23fda98b2e3ac259d8d67585f671
        with:
          context: ./load-tests/echo
          file: Dockerfile
          push: true
          tags: ${{ secrets.NAMESPACE }}/echo-load-test:${{ github.sha }}
          labels: |
            org.opencontainers.image.source=${{ github.event.repository.html_url }}
            org.opencontainers.image.revision=${{ github.sha }}

  update_job:
    name: Update the job tag
    runs-on: ubuntu-latest
    needs: push_to_registry
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4
        
      - name: Update the job tag
        run: |
          sed -i "s|image: ${{ secrets.NAMESPACE }}/echo-load-test:.*|image: ${{ secrets.NAMESPACE }}/echo-load-test:${{ github.sha }}|" ./argo-rollouts/templates/echo-load-test-job.yaml
          git add ./argo-rollouts/templates/echo-load-test-job.yaml
          git commit -m "Update the job tag to ${{ github.sha }}"
          git push